# -*- coding: utf-8 -*-
"""Tool metadata for static SEO pages. Calculator logic lives in assets/js/tools.js (same slugs)."""

CATEGORIES = [
    ("finance", "Finance & Money", "$", "Mortgages, loans, savings, investing and business math."),
    ("math", "Math & Algebra", "∑", "Percentages, equations, fractions, statistics and more."),
    ("health", "Health & Fitness", "♥", "BMI, calories, ideal weight and hydration."),
    ("datetime", "Date & Time", "⏱", "Ages, date differences, deadlines and durations."),
    ("convert", "Converters", "⇄", "Units, number bases and Roman numerals."),
    ("random", "Random & Games", "⚄", "Secure random numbers, dice, coins and passwords."),
]

def T(slug, name, cat, desc, intro, formula, example, faq, kw="", hot=False):
    return dict(slug=slug, name=name, cat=cat, desc=desc, intro=intro, formula=formula, example=example, faq=faq, kw=kw, hot=hot)

TOOLS = [
 # ---------------- FINANCE ----------------
 T("mortgage-calculator", "Mortgage Calculator", "finance",
   "Estimate your monthly mortgage payment including taxes, insurance and HOA.",
   "Enter the home price, your down payment, the interest rate and the loan term to see your full monthly housing cost — principal and interest plus property tax, homeowners insurance and HOA dues — along with the total interest you will pay over the life of the loan.",
   "M = P × r(1 + r)ⁿ ÷ [(1 + r)ⁿ − 1]   where P = loan amount, r = monthly rate, n = number of payments",
   "A $450,000 home with $90,000 down at 6.5% over 30 years gives a loan of $360,000 and a principal-and-interest payment of about $2,275 per month.",
   [("How much down payment do I need?", "Many conventional loans allow 3–5% down, but putting 20% down usually avoids private mortgage insurance (PMI) and lowers your monthly payment."),
    ("Does a 15-year mortgage save money?", "Yes. The monthly payment is higher, but you pay interest for half as long and 15-year rates are typically lower, so total interest can fall by more than half."),
    ("What is included in PITI?", "PITI stands for Principal, Interest, Taxes and Insurance — the four parts of a typical monthly mortgage payment. This calculator adds HOA dues too.")],
   "home loan house payment amortization piti refinance", True),
 T("loan-emi-calculator", "Loan & EMI Calculator", "finance",
   "Calculate the equated monthly instalment (EMI), total interest and total cost of any loan.",
   "Use this for personal loans, car loans, student loans or business loans. Enter the amount, annual interest rate and tenure to see your fixed monthly instalment and how much of what you repay is interest.",
   "EMI = P × r × (1 + r)ⁿ ÷ [(1 + r)ⁿ − 1]",
   "A 25,000 loan at 9% for 5 years has an EMI of about 518.96 and total interest of roughly 6,138.",
   [("What does EMI mean?", "Equated Monthly Instalment — a fixed payment that covers both interest and principal so the loan is fully repaid by the end of the term."),
    ("How can I reduce my EMI?", "Choose a longer tenure, negotiate a lower rate, or make a larger down payment. A longer tenure lowers the EMI but increases total interest."),
    ("Does prepayment help?", "Yes. Extra payments reduce the outstanding principal, which cuts future interest; check your lender's prepayment terms first.")],
   "emi personal loan car loan auto loan student loan interest", True),
 T("compound-interest-calculator", "Compound Interest Calculator", "finance",
   "See how your money grows with compound interest and regular monthly contributions.",
   "Compound interest means you earn returns on your returns. Enter a starting balance, a monthly contribution, an expected annual return and a time horizon to project your future balance.",
   "A = P(1 + r/n)^(nt) + PMT × [((1 + r/n)^(nt) − 1) ÷ (r/n)]",
   "$10,000 plus $300 a month at 7% compounded monthly grows to roughly $197,600 after 20 years — more than half of it interest.",
   [("What is the Rule of 72?", "Divide 72 by the annual return to estimate how many years it takes money to double. At 8%, money doubles in about 9 years."),
    ("Does compounding frequency matter?", "More frequent compounding earns slightly more, but the rate and time horizon matter far more than monthly vs. daily compounding."),
    ("Are these returns guaranteed?", "No. Investment returns vary year to year; use a conservative rate for planning.")],
   "investment growth savings future value rule of 72", True),
 T("savings-goal-calculator", "Savings Goal Calculator", "finance",
   "Find out how much to save each month to reach any savings goal on time.",
   "Whether it's an emergency fund, a down payment or a dream trip, enter your target, what you've already saved, the interest rate you expect and your deadline.",
   "PMT = (Goal − Current × (1 + r)ⁿ) × r ÷ [(1 + r)ⁿ − 1]",
   "To reach $50,000 in 5 years with $5,000 saved at 4.5%, you need to save roughly $651 per month.",
   [("How big should an emergency fund be?", "A common guideline is 3–6 months of essential expenses; more if your income is irregular."),
    ("Where should short-term savings go?", "Money needed within a few years is usually kept in high-yield savings accounts, term deposits or similar low-risk products.")],
   "save money target emergency fund down payment"),
 T("retirement-calculator", "Retirement Calculator", "finance",
   "Project your retirement nest egg and see if you're on track for the income you want.",
   "Enter your age, retirement age, current savings, monthly contributions and expected return. The calculator compares your projected nest egg to the amount needed to fund your target income using a safe-withdrawal rate.",
   "Target nest egg = Desired annual income ÷ Withdrawal rate",
   "Wanting $60,000 a year at a 4% withdrawal rate requires a nest egg of about $1.5 million.",
   [("What is the 4% rule?", "A rule of thumb suggesting you can withdraw about 4% of your portfolio in the first year of retirement, adjusting for inflation after, with a low chance of running out over 30 years."),
    ("Should I include pensions or social security?", "Yes — subtract guaranteed income from your desired income before calculating the nest egg you need."),
    ("What return should I assume?", "Many planners use 5–7% before retirement for diversified portfolios; lower is more conservative.")],
   "fire 401k rrsp pension nest egg 4% rule", True),
 T("credit-card-payoff-calculator", "Credit Card Payoff Calculator", "finance",
   "Find out how long it will take to pay off a credit card and how much interest you'll pay.",
   "Enter your balance, the card's APR and what you can pay each month. See your debt-free date and total interest — then try a higher payment to see how much faster you get out of debt.",
   "Each month: Balance = Balance × (1 + APR/12) − Payment",
   "A $6,000 balance at 22.9% APR with $250 monthly payments takes 33 months (2 years 9 months) and costs about $2,100 in interest.",
   [("Avalanche or snowball?", "The avalanche method (highest APR first) saves the most interest; the snowball method (smallest balance first) gives faster wins that keep some people motivated."),
    ("Does a balance transfer help?", "A 0% transfer offer can save a lot if you clear the balance before the promo ends — factor in the transfer fee.")],
   "debt payoff apr interest balance transfer"),
 T("roi-calculator", "ROI Calculator", "finance",
   "Calculate return on investment and annualized return (CAGR) for any investment.",
   "Compare investments, marketing campaigns, domains or property by entering what you put in, what you got back and how long you held it.",
   "ROI = (Return − Cost) ÷ Cost × 100      CAGR = (Return ÷ Cost)^(1/years) − 1",
   "Investing $10,000 and receiving $14,500 after 3 years is a 45% ROI or about 13.2% per year.",
   [("Why is annualized ROI important?", "A 45% gain over 3 years is very different from 45% over 10 years. Annualizing lets you compare investments with different holding periods."),
    ("Does ROI include costs?", "It should — include fees, taxes and maintenance in the cost for a true picture.")],
   "return on investment cagr annualized return profit"),
 T("inflation-calculator", "Inflation Calculator", "finance",
   "See how inflation erodes purchasing power over time.",
   "Estimate what today's money will cost in the future — or what a future amount is worth in today's dollars — using an average inflation rate.",
   "Future cost = Amount × (1 + inflation)^years",
   "At 3% inflation, $1,000 today will need about $1,344 in 10 years to buy the same things.",
   [("What inflation rate should I use?", "Many central banks target around 2% per year; long-run historical averages in many developed economies are roughly 2–4%.")],
   "purchasing power cpi cost of living"),
 T("salary-hourly-calculator", "Salary to Hourly Calculator", "finance",
   "Convert between annual salary, monthly, weekly, daily and hourly pay.",
   "Enter any pay amount and period plus your working hours to see the equivalent pay for every other period.",
   "Hourly = Annual salary ÷ (Hours per week × Weeks per year)",
   "$65,000 per year at 40 hours × 52 weeks is $31.25 per hour.",
   [("How many working hours are in a year?", "A full-time 40-hour week over 52 weeks is 2,080 hours. Subtract vacation weeks for a more precise figure.")],
   "wage pay rate annual income hourly rate"),
 T("tip-calculator", "Tip & Split Calculator", "finance",
   "Work out the tip and split the bill between any number of people.",
   "Enter the bill, choose a tip percentage and the number of people to see each person's share.",
   "Per person = Bill × (1 + Tip%) ÷ People",
   "An $86.40 bill with an 18% tip split three ways is $33.98 each.",
   [("How much should I tip?", "Customs vary by country. In the US and Canada 15–20% is typical at sit-down restaurants; many other countries include service in the bill.")],
   "gratuity bill split restaurant"),
 T("discount-calculator", "Discount Calculator", "finance",
   "Calculate sale prices, stacked discounts and how much you save.",
   "Enter the original price and discount — add an extra coupon and sales tax if you like — to see the final price and your real savings.",
   "Final = Price × (1 − d₁) × (1 − d₂) × (1 + tax)",
   "25% off then an extra 10% off is a 32.5% total discount, not 35%.",
   [("Are stacked discounts additive?", "No. The second discount applies to the already-reduced price, so 25% + 10% equals 32.5% off.")],
   "sale price percent off coupon savings"),
 T("sales-tax-calculator", "Sales Tax / VAT / GST Calculator", "finance",
   "Add or remove sales tax, VAT or GST from any price.",
   "Switch between adding tax to a net price and extracting the tax already included in a gross price.",
   "Gross = Net × (1 + rate)      Net = Gross ÷ (1 + rate)",
   "$100 plus 13% HST is $113. A $113 receipt includes $13 of tax.",
   [("How do I remove tax from a total?", "Divide the total by 1 plus the tax rate. For 13% tax: $113 ÷ 1.13 = $100.")],
   "vat gst hst reverse tax"),
 T("profit-margin-calculator", "Profit Margin Calculator", "finance",
   "Calculate gross margin, markup and profit per unit.",
   "Enter your cost and selling price to see margin and markup — two numbers that are often confused.",
   "Margin = (Price − Cost) ÷ Price      Markup = (Price − Cost) ÷ Cost",
   "Buying at $40 and selling at $65 is a 38.5% margin but a 62.5% markup.",
   [("What's the difference between margin and markup?", "Margin is profit as a share of the selling price; markup is profit as a share of cost. The same deal always has a higher markup than margin.")],
   "markup gross margin pricing ecommerce"),
 T("break-even-calculator", "Break-Even Calculator", "finance",
   "Find how many units you must sell to cover fixed costs.",
   "Essential for pricing, launching products and planning a business: enter fixed costs, price and variable cost per unit.",
   "Break-even units = Fixed costs ÷ (Price − Variable cost)",
   "$12,000 fixed costs, a $49 price and $18 variable cost means 388 units to break even.",
   [("What counts as a fixed cost?", "Costs that don't change with volume in the short term — rent, salaries, software subscriptions, insurance.")],
   "business startup contribution margin pricing"),
 # ---------------- MATH ----------------
 T("percentage-calculator", "Percentage Calculator", "math",
   "Five percentage calculators in one: percent of, what percent, percent change, increase and decrease.",
   "Pick what you want to find and enter X and Y. Results update instantly as you type.",
   "X% of Y = X ÷ 100 × Y      % change = (New − Old) ÷ |Old| × 100",
   "15% of 240 is 36. Going from 80 to 100 is a 25% increase.",
   [("How do I calculate a percentage increase?", "Subtract the old value from the new value, divide by the old value and multiply by 100."),
    ("Is a 50% drop reversed by a 50% gain?", "No. 100 → 50 is −50%, but 50 → 100 is +100%.")],
   "percent of percent change increase decrease", True),
 T("scientific-calculator", "Scientific Calculator", "math",
   "A free online scientific calculator with trig, logs, powers, roots and factorials.",
   "Type or tap an expression. Supports sin, cos, tan and their inverses (degrees or radians), ln, log, square roots, powers (^), factorial (!), percent, π, e and your previous answer (Ans).",
   "Order of operations: brackets → powers → × ÷ → + −",
   "Try: 2^10 + sqrt(144) × sin(30) → 1030",
   [("Degrees or radians?", "Use DEG for everyday geometry; RAD for calculus and physics formulas."),
    ("Does it support implicit multiplication?", "Yes — 2π and 3(4+1) work as expected.")],
   "calculator trig sin cos tan log online calculator", True),
 T("quadratic-equation-solver", "Quadratic Equation Solver", "math",
   "Solve ax² + bx + c = 0 with real or complex roots, discriminant and vertex.",
   "Enter coefficients a, b and c. The solver shows both roots, the discriminant, the vertex and the axis of symmetry.",
   "x = [−b ± √(b² − 4ac)] ÷ 2a",
   "x² − 3x − 10 = 0 has roots x = 5 and x = −2.",
   [("What does the discriminant tell me?", "If b² − 4ac > 0 there are two real roots; = 0 one repeated root; < 0 two complex roots.")],
   "algebra roots parabola quadratic formula"),
 T("gcd-lcm-calculator", "GCD & LCM Calculator", "math",
   "Find the greatest common divisor and least common multiple of two or more numbers.",
   "Enter whole numbers separated by commas. Uses the Euclidean algorithm.",
   "gcd(a, b) = gcd(b, a mod b)      lcm(a, b) = a × b ÷ gcd(a, b)",
   "gcd(12, 18, 30) = 6 and lcm(12, 18, 30) = 180.",
   [("Where is LCM used?", "Adding fractions (common denominators), scheduling repeating events and gear ratios.")],
   "hcf gcf greatest common factor lowest common multiple"),
 T("prime-factorization-calculator", "Prime Factorization Calculator", "math",
   "Break any whole number into its prime factors and check if it's prime.",
   "Enter a whole number to get its prime factorization in exponent form, the number of divisors and whether it is prime.",
   "n = p₁^a₁ × p₂^a₂ × … × pₖ^aₖ      divisors = (a₁+1)(a₂+1)…(aₖ+1)",
   "55,993 = 7 × 19 × 421, so it has 8 divisors.",
   [("Is 1 a prime number?", "No. A prime has exactly two distinct divisors — 1 and itself — and 1 has only one.")],
   "prime number checker factors factor tree"),
 T("statistics-calculator", "Statistics Calculator", "math",
   "Mean, median, mode, range, variance and standard deviation for any data set.",
   "Paste numbers separated by commas, spaces or new lines. All statistics update instantly.",
   "σ = √[Σ(x − μ)² ÷ N]      s = √[Σ(x − x̄)² ÷ (n − 1)]",
   "For 4, 8, 15, 16, 23, 42 the mean is 18 and the median is 15.5.",
   [("Population or sample standard deviation?", "Use population (σ) when your data is the entire group; sample (s) when it's a sample from a larger group.")],
   "mean median mode average standard deviation variance"),
 T("fraction-calculator", "Fraction Calculator", "math",
   "Add, subtract, multiply and divide fractions and mixed numbers — simplified automatically.",
   "Enter fractions like 3/4, −2/5 or mixed numbers like 1 1/2.",
   "a/b + c/d = (ad + bc) ÷ bd",
   "3/4 + 5/6 = 19/12 = 1 7/12.",
   [("How do you simplify a fraction?", "Divide the numerator and denominator by their greatest common divisor.")],
   "fractions mixed numbers simplify"),
 T("exponent-log-calculator", "Exponent & Logarithm Calculator", "math",
   "Compute powers, roots and logarithms in any base.",
   "Enter a base and a value to get bˣ, log base b of x, natural log, common log and roots.",
   "log_b(x) = ln(x) ÷ ln(b)",
   "2¹⁰ = 1,024 and log₂(1,024) = 10.",
   [("What is a logarithm?", "The exponent you'd raise the base to in order to get the number: log₂(8) = 3 because 2³ = 8.")],
   "power root log ln exponent"),
 T("ratio-proportion-calculator", "Ratio & Proportion Calculator", "math",
   "Solve proportions A : B = C : X and simplify ratios.",
   "Useful for recipes, scale drawings, mixing and currency.",
   "X = B × C ÷ A",
   "3 : 4 = 15 : X gives X = 20.",
   [("How do I scale a recipe?", "Treat the original and new servings as a ratio and multiply every ingredient by new ÷ original.")],
   "ratio proportion scale"),
 # ---------------- HEALTH ----------------
 T("bmi-calculator", "BMI Calculator", "health",
   "Calculate Body Mass Index in metric or imperial units, with healthy weight range.",
   "Choose metric or imperial, then enter weight and height. You'll see your BMI category and the healthy weight range for your height.",
   "BMI = weight (kg) ÷ height (m)²",
   "72 kg at 1.75 m gives a BMI of 23.5 — within the healthy range.",
   [("Is BMI accurate?", "BMI is a quick screening tool. It doesn't distinguish muscle from fat, so athletes and older adults may be misclassified."),
    ("What is a healthy BMI?", "For most adults, 18.5 to 24.9.")],
   "body mass index weight height obesity", True),
 T("calorie-calculator", "Calorie Calculator (TDEE)", "health",
   "Estimate your daily calories for maintenance, weight loss or gain.",
   "Based on the Mifflin–St Jeor equation, one of the most validated BMR formulas, multiplied by an activity factor.",
   "BMR = 10W + 6.25H − 5A + s   (s = +5 male, −161 female)",
   "A moderately active 35-year-old man, 78 kg and 178 cm, needs about 2,670 kcal/day to maintain weight.",
   [("How many calories are in a kilogram of fat?", "Roughly 7,700 kcal, so a 550 kcal daily deficit is about 0.5 kg per week.")],
   "tdee bmr calories diet weight loss"),
 T("ideal-weight-calculator", "Ideal Weight Calculator", "health",
   "Compare ideal body weight from four classic formulas.",
   "Shows Devine, Robinson, Miller and Hamwi estimates alongside the healthy BMI range.",
   "Devine (men) = 50 kg + 2.3 kg per inch over 5 ft",
   "A 175 cm man has a Devine ideal weight of about 70.5 kg.",
   [("Which formula is best?", "None is perfect; they were designed for dosing medication. Treat them as a range, not a target.")],
   "ibw healthy weight"),
 T("water-intake-calculator", "Water Intake Calculator", "health",
   "Estimate how much water to drink each day.",
   "Based on body weight with adjustments for exercise and climate.",
   "Litres ≈ 0.033 × kg + 0.35 per 30 min exercise",
   "A 70 kg person exercising 30 minutes needs about 2.7 L.",
   [("Does coffee count?", "Yes, most beverages and water-rich foods contribute to daily fluid intake.")],
   "hydration drink water"),
 # ---------------- DATE & TIME ----------------
 T("age-calculator", "Age Calculator", "datetime",
   "Calculate your exact age in years, months, days — and days until your next birthday.",
   "Enter a date of birth (and optionally another date) to get an exact age plus totals in months, weeks, days and hours.",
   "Age = Target date − Birth date (calendar-aware)",
   "Someone born on 15 May 1990 turns 36 on 15 May 2026.",
   [("How is age calculated exactly?", "Full years are counted first, then remaining months, then days — borrowing days from the previous month when needed.")],
   "birthday how old am i date of birth", True),
 T("date-difference-calculator", "Date Difference Calculator", "datetime",
   "Count days, weeks and business days between two dates.",
   "Pick a start and end date to see the exact number of days, weeks + days, weekdays and approximate months and years.",
   "Days = (End − Start) ÷ 86,400,000 ms",
   "1 January to 31 December is 364 days (365 including the end date).",
   [("Are holidays excluded from business days?", "Only weekends are excluded; subtract public holidays in your region manually.")],
   "days between dates countdown weeks"),
 T("add-days-calculator", "Add or Subtract Days Calculator", "datetime",
   "Find the date that is N calendar or business days from any date.",
   "Useful for deadlines, notice periods, shipping estimates and due dates.",
   "Result = Start date ± N days",
   "90 days after 1 March is 30 May.",
   [("Can I count backwards?", "Yes, enter a negative number of days.")],
   "deadline due date business days"),
 T("time-duration-calculator", "Time Duration Calculator", "datetime",
   "Calculate hours and minutes between two times, minus breaks.",
   "Great for timesheets and shift work — handles overnight shifts that cross midnight.",
   "Duration = End − Start − Break (add 24 h if End < Start)",
   "09:15 to 17:40 with a 30-minute break is 7 h 55 min (7.92 hours).",
   [("How do I convert minutes to decimal hours?", "Divide minutes by 60: 55 minutes is 0.92 hours.")],
   "hours worked timesheet shift"),
 # ---------------- CONVERTERS ----------------
 T("unit-converter", "Unit Converter", "convert",
   "Convert length, weight, temperature, area, volume, speed, data and time units.",
   "Choose a category, enter a value and pick units — every other unit in the category is shown at once.",
   "Result = Value × (from factor ÷ to factor)   ·   °F = °C × 9/5 + 32",
   "1 mile = 1.609344 km. 100 °F = 37.78 °C.",
   [("Why are there two gallons?", "The US gallon is 3.785 L; the imperial (UK) gallon is 4.546 L."),
    ("KB or KiB?", "KB (kilobyte) is 1,000 bytes; KiB (kibibyte) is 1,024 bytes.")],
   "convert km miles kg lbs celsius fahrenheit metric imperial", True),
 T("number-base-converter", "Number Base Converter", "convert",
   "Convert between decimal, binary, octal, hexadecimal and base 36 — any size.",
   "Uses arbitrary-precision integers, so very large numbers convert exactly.",
   "Value = Σ digitᵢ × baseⁱ",
   "55993 in hexadecimal is DAB9; in binary it's 1101101010111001.",
   [("Why do programmers use hexadecimal?", "Each hex digit maps to exactly 4 binary bits, making binary data compact and readable.")],
   "binary hex octal decimal base converter"),
 T("roman-numeral-converter", "Roman Numeral Converter", "convert",
   "Convert numbers to Roman numerals and back.",
   "Enter a number from 1 to 3999 or a Roman numeral like MMXXVI.",
   "I=1 · V=5 · X=10 · L=50 · C=100 · D=500 · M=1000",
   "2026 = MMXXVI.",
   [("Why does IV mean 4?", "A smaller numeral before a larger one is subtracted: IV = 5 − 1.")],
   "roman numerals"),
 # ---------------- RANDOM ----------------
 T("random-number-generator", "Random Number Generator", "random",
   "Generate cryptographically secure random numbers in any range — unique or with repeats.",
   "Uses your browser's crypto.getRandomValues() for unbiased, secure randomness. Ideal for draws, raffles, sampling and games.",
   "Result ∈ [min, max], uniformly distributed",
   "Pick 6 unique numbers from 1–49 for a raffle draw.",
   [("Is it truly random?", "It uses a cryptographically secure pseudorandom generator seeded by your operating system — suitable for fair draws.")],
   "rng random picker raffle draw lottery numbers", True),
 T("dice-coin-roller", "Dice Roller & Coin Flip", "random",
   "Roll d4, d6, d8, d10, d12, d20 dice or flip coins online.",
   "Choose a die (or coin) and how many to roll. Great for tabletop games and quick decisions.",
   "Each face has probability 1 ÷ sides",
   "Rolling two d6 gives totals from 2 to 12; 7 is the most likely.",
   [("What's the most common total with two dice?", "7 — six of the 36 combinations add up to 7.")],
   "dice d20 coin flip heads tails"),
 T("password-generator", "Password Generator", "random",
   "Create strong random passwords and PINs — generated locally, never sent anywhere.",
   "Choose a length and character set. Entropy is shown so you know how strong the password is.",
   "Entropy (bits) = Length × log₂(Charset size)",
   "A 20-character password from 70 symbols has about 123 bits of entropy.",
   [("How long should a password be?", "At least 14–16 random characters for important accounts; use a password manager to store them.")],
   "strong password secure pin generator"),
]
